import type { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Blue Hoodie - M",
    currentStock: 18,
    threshold: 5,
    unitPrice: 42,
    reorderLeadDays: 3,
    sales: [
      { date: "Mar 18", unitsSold: 3 },
      { date: "Mar 19", unitsSold: 2 },
      { date: "Mar 20", unitsSold: 4 },
      { date: "Mar 21", unitsSold: 3 },
      { date: "Mar 22", unitsSold: 5 },
      { date: "Mar 23", unitsSold: 4 },
      { date: "Mar 24", unitsSold: 3 },
      { date: "Mar 25", unitsSold: 4 },
      { date: "Mar 26", unitsSold: 5 },
      { date: "Mar 27", unitsSold: 4 },
      { date: "Mar 28", unitsSold: 3 },
      { date: "Mar 29", unitsSold: 4 },
      { date: "Mar 30", unitsSold: 5 },
      { date: "Mar 31", unitsSold: 4 },
    ],
  },
  {
    id: "p2",
    name: "Blue Hoodie - L",
    currentStock: 34,
    threshold: 8,
    unitPrice: 42,
    reorderLeadDays: 4,
    sales: [
      { date: "Mar 18", unitsSold: 1 },
      { date: "Mar 19", unitsSold: 2 },
      { date: "Mar 20", unitsSold: 2 },
      { date: "Mar 21", unitsSold: 1 },
      { date: "Mar 22", unitsSold: 3 },
      { date: "Mar 23", unitsSold: 2 },
      { date: "Mar 24", unitsSold: 2 },
      { date: "Mar 25", unitsSold: 3 },
      { date: "Mar 26", unitsSold: 2 },
      { date: "Mar 27", unitsSold: 2 },
      { date: "Mar 28", unitsSold: 3 },
      { date: "Mar 29", unitsSold: 2 },
      { date: "Mar 30", unitsSold: 1 },
      { date: "Mar 31", unitsSold: 2 },
    ],
  },
  {
    id: "p3",
    name: "Red T-Shirt - S",
    currentStock: 9,
    threshold: 4,
    unitPrice: 24,
    reorderLeadDays: 2,
    sales: [
      { date: "Mar 18", unitsSold: 1 },
      { date: "Mar 19", unitsSold: 1 },
      { date: "Mar 20", unitsSold: 2 },
      { date: "Mar 21", unitsSold: 1 },
      { date: "Mar 22", unitsSold: 2 },
      { date: "Mar 23", unitsSold: 1 },
      { date: "Mar 24", unitsSold: 1 },
      { date: "Mar 25", unitsSold: 2 },
      { date: "Mar 26", unitsSold: 1 },
      { date: "Mar 27", unitsSold: 1 },
      { date: "Mar 28", unitsSold: 2 },
      { date: "Mar 29", unitsSold: 1 },
      { date: "Mar 30", unitsSold: 2 },
      { date: "Mar 31", unitsSold: 1 },
    ],
  },
];
